# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/lemonadep/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lemonadep)

$(call add-radio-file-sha1-checked,radio/abl.img,c1851a404424b7ea96a1d4243f02ef45d6eace7f)
$(call add-radio-file-sha1-checked,radio/aop.img,180294afcff912a73b3b78ef3bec1d99c995f50f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,3c94de7025c3849a2c6130ee4326afc8b005bead)
$(call add-radio-file-sha1-checked,radio/cpucp.img,ba7575c18f6af87f930aaa56a58c0c7391b8dbbc)
$(call add-radio-file-sha1-checked,radio/devcfg.img,9eb62c3f8d4b3a14344840b14a3c32d19e4ce0f9)
$(call add-radio-file-sha1-checked,radio/dsp.img,634718247c9670c0c2aab842804ea74c3f274396)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e5b5b6aa4e160a11b9962f328561dd0c9ccac273)
$(call add-radio-file-sha1-checked,radio/hyp.img,fbb79628e6549c577f674e70440681e5c441c1f5)
$(call add-radio-file-sha1-checked,radio/imagefv.img,03e4aad086c47b9f5b61cb1f51d7cce911f981f9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,be65e7227d7474b93d4968da50c8e518e2cf647d)
$(call add-radio-file-sha1-checked,radio/modem.img,66c1352517940f4d8c61160b1726a82edb3580bc)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,316d679218647a1d6b2dfb69071e84e6417fc53d)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,70c1fb07ea5d63af49361d57b2a5f5d22a7b5612)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,95b169e0e406a2d878410292a8b39e5d82cb9af3)
$(call add-radio-file-sha1-checked,radio/qupfw.img,cda05e3dc47620a46f89cc47f4b44aeb9c8cc827)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,d1e3a6ea3894ca6d49d04f0a889447d526f92a48)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,939d99f9d52d870a37c2feb05824916c7917d39d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,53b199c092db9388d26db2bf1a918be059802793)
$(call add-radio-file-sha1-checked,radio/xbl.img,c24b8aa584e5b37fdf807399919d0b4e7b19a36c)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,0265454091afb9c8e4da60a6304e5feeceb8ddc6)

endif
